"""Base

Revision ID: 63ac71f68ebd
Revises: 
Create Date: 2024-09-12 20:40:55.179590

"""
from typing import Sequence, Union
import sqlmodel
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '63ac71f68ebd'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('account')
    op.add_column('customer', sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=False))
    op.add_column('customer', sa.Column('phone', sqlmodel.sql.sqltypes.AutoString(), nullable=False))
    op.add_column('customer', sa.Column('address', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.add_column('customer', sa.Column('email', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.add_column('order', sa.Column('product_id', sa.Integer(), nullable=False))
    op.add_column('order', sa.Column('client_id', sa.Integer(), nullable=False))
    op.add_column('order', sa.Column('payment', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.add_column('order', sa.Column('order_date', sa.Date(), nullable=False))
    op.add_column('order', sa.Column('delivery_date', sa.Date(), nullable=True))
    op.add_column('order', sa.Column('quantity', sa.Integer(), nullable=False))
    op.add_column('order', sa.Column('discount', sa.Integer(), nullable=True))
    op.add_column('product', sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=False))
    op.add_column('product', sa.Column('description', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.add_column('product', sa.Column('category', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.add_column('purchases', sa.Column('product_id', sa.Integer(), nullable=False))
    op.add_column('purchases', sa.Column('supplier_id', sa.Integer(), nullable=False))
    op.add_column('purchases', sa.Column('quantity', sa.Integer(), nullable=False))
    op.add_column('purchases', sa.Column('price', sa.Float(), nullable=False))
    op.add_column('purchases', sa.Column('payment_method', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.add_column('purchases', sa.Column('purchase_date', sa.Date(), nullable=False))
    op.add_column('stock', sa.Column('product_id', sa.Integer(), nullable=False))
    op.add_column('stock', sa.Column('quantity', sa.Integer(), nullable=False))
    op.add_column('stock', sa.Column('last_price', sa.Float(), nullable=False))
    op.add_column('stock', sa.Column('total', sa.Float(), nullable=False))
    op.add_column('supplier', sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=False))
    op.add_column('supplier', sa.Column('address', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.add_column('supplier', sa.Column('cnpj', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.add_column('supplier', sa.Column('contact', sqlmodel.sql.sqltypes.AutoString(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('supplier', 'contact')
    op.drop_column('supplier', 'cnpj')
    op.drop_column('supplier', 'address')
    op.drop_column('supplier', 'name')
    op.drop_column('stock', 'total')
    op.drop_column('stock', 'last_price')
    op.drop_column('stock', 'quantity')
    op.drop_column('stock', 'product_id')
    op.drop_column('purchases', 'purchase_date')
    op.drop_column('purchases', 'payment_method')
    op.drop_column('purchases', 'price')
    op.drop_column('purchases', 'quantity')
    op.drop_column('purchases', 'supplier_id')
    op.drop_column('purchases', 'product_id')
    op.drop_column('product', 'category')
    op.drop_column('product', 'description')
    op.drop_column('product', 'name')
    op.drop_column('order', 'discount')
    op.drop_column('order', 'quantity')
    op.drop_column('order', 'delivery_date')
    op.drop_column('order', 'order_date')
    op.drop_column('order', 'payment')
    op.drop_column('order', 'client_id')
    op.drop_column('order', 'product_id')
    op.drop_column('customer', 'email')
    op.drop_column('customer', 'address')
    op.drop_column('customer', 'phone')
    op.drop_column('customer', 'name')
    op.create_table('account',
    sa.Column('id', sa.INTEGER(), sa.Identity(always=False, start=1, increment=1), autoincrement=True, nullable=False),
    sa.PrimaryKeyConstraint('id', name='PK__account__3213E83F88DE2E60')
    )
    # ### end Alembic commands ###
